port: "8080"

#production db conf from docker-compose
mongo_db:
  host: "mongodb"
  port: "27017"
  timeout: 10s
redis_db:
  host: "redis"
  port: "6379"
  DB: 0
#db config for local development
mongo_dev_db:
  host: "localhost"
  port: "27017"
  timeout: 10s
#redis db config
redis_dev_db:
  host: "localhost"
  port: "6379"
  DB: 0