port: "8080"

#production db conf from docker-compose
db:
#db config for local development
dev_db:
  host: "localhost"
  port: "27017"
  username: "mongo"
  database: "budget_app"
  timeout: 10s
#redis db config
redis_dev_db:
  host: "localhost"
  port: "6379"
  DB: 0